# Generated by Django 5.0.6 on 2024-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="building",
            field=models.CharField(
                choices=[
                    ("main_building", "главный корпус"),
                    ("baizak", "байзак"),
                    ("gym", "спортзал"),
                ],
                max_length=100,
            ),
        ),
    ]
