# Generated by Django 5.0.6 on 2024-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="department",
            field=models.CharField(
                choices=[("AHD", "AHD"), ("DIT", "DIT")], default="admin", max_length=10
            ),
            preserve_default=False,
        ),
    ]
