# Generated by Django 5.0.6 on 2024-05-31 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('AHD', 'AHD'), ('DIT', 'DIT')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('urgent', 'Срочно'), ('not_urgent', 'Не срочно'), ('very_urgent', 'Очень срочно')], default='not_urgent', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(choices=[('main', 'Главный'), ('baizak', 'Байзак'), ('gym', 'Спортзал')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('accepted', 'Принято'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='problem_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.problem'),
        ),
    ]
