# Generated by Django 5.0.6 on 2024-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_problem_order_urgency_alter_order_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('accepted', 'Принято'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('freeze', 'Заморожен')], default='submitted', max_length=20),
        ),
    ]
