# Generated by Django 5.0.6 on 2024-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("sender", "Отправитель"),
                    ("ahd", "АХД"),
                    ("dit", "ДИТ"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
