# Generated by Django 5.0.6 on 2024-06-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sender', 'Отправитель'), ('ahd', 'АХД'), ('dit', 'ДИТ'), ('head', 'HEAD'), ('admin', 'Admin')], max_length=10),
        ),
    ]
